###
# Spring settings
###
spring:
  #Jpa settings
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true


#Application settings
application:
  name: ontherun

#Server settings
server:
  port: 8080

