server:
  port: 8080

spring:
  application:
    name: ontherun
  datasource:
    driver-class-name: org.postgresql.Driver
    username: 'postgres'
    password: 'toor'
    url: jdbc:postgresql://localhost:5432/ontherun
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dealect: org.hibernate.dealect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'