###
# Spring settings
###
spring:
  #Jpa settings
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
      org:
        hibernate:
          # Envers settings
          envers:
            audit_table_suffix: '_history'
            revision_field_name: 'history_info_id'
            revision_type_field_name: 'type'

  security:
    jwt:
      # Secret used for signing JWT token.
      secret-key: 25442A472D4B614E645267556B58703273357638792F423F4528482B4D6251655368566D597133743677397A24432646294A404E635266556A576E5A72347537
      #Validity time of JWT token in milliseconds.
      expirationTime: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

#Application settings
application:
  name: ontherun

#Server settings
server:
  port: 8080

