server:
  port: 8080

spring:
  application:
    name: ontherun
  datasource:
    driver-class-name: org.postgresql.Driver
    username: 'postgres'
    password: 'root'
    url: jdbc:postgresql://postgres:5432/ontherun
  jpa:
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
    show-sql: 'true'